config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/index'
  get 'users/edit'
  get "home/about" => "homes#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  get "users/:id" => "users#show", as: :mypage
  resources :books
  resources :users, only: [:show, :index, :edit, :update]
  resources :homes, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :opinion, presence: true
	validates :opinion, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  attachment :image

  validates :name, length: {in: 2..20}
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :email, presence: true
  validates :introduct, length: {maximum: 50}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	  # before_action :authenticate_user!
	  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	mypage_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
	def new
		@book = Book.new
		@book.user_id = current_user.id
		@user = current_user
	end

	def create
		@user = current_user
		@books = Book.all
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "Book was successfully created."
		    redirect_to book_path(@book)
		else
			render :index
		end

	end

	def index
		@books = Book.all
		# @user = User.find(params[:id])
		@user = current_user
		@book = Book.new
	end

	def show
		@showbook = Book.find(params[:id])
		@user = Book.find(params[:id])
		@book = Book.new
		# @newbook = Book.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end

	def update
		book = Book.find(params[:id])
		if book.update(book_params)
			flash[:notice] = "Book was successfully edited"
		    redirect_to book_path(book)
		else
			redirect_to book_path(book)
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end


	private
	def book_params
		params.require(:book).permit(:title, :opinion)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
	end


	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def index
    @book = Book.new
  	@users = User.all
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
       redirect_to user_path(@user.id)
    else
      render :edit
    end

  end




  private
  def user_params
  	params.require(:user).permit(:name, :opinion, :introduct, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="main-side">
	<div class="user info">
		<h2>User info</h2>
		<table class="table table-striped user-info-table">

			<div><%= attachment_image_tag @user, :image, class: "profile-img2", fallback: "no_image.jpg" %></div>
			<div class="space1"></div>

			<tr>
				<th> name</th>
				<td><%= @user.name %></td>
			</tr>
			<tr>
				<th> introduction</th>
				<td><%= @user.introduct %></td>
			</tr>
		</table>
		<%=link_to "", edit_user_path(@user), class:"glyphicon glyphicon-wrench field-size btn btn-default edit_user_#{@user.id}" %>
	</div>



	<div class="new-book">
		<%= form_for(@book) do |f| %>
		<h2>New book</h2>
		<h4>Title</h4>
		<%= f.text_field :title, class:"field-size" %><br>
		<h4>Opinion</h4>
		<%= f.text_area :opinion, class:"field-size" %><br>
		<%= f.submit "Create book", class:"field-size btn btn-primary" %>
		<% end %>
	</div>

</div>

app/views/books/edit.html.erb
<div class="book-edit">
	<h2>Editing Book</h2>
	<%= form_for(@book) do |f| %>
	<h4> Title</h4>
	<%= f.text_field :title, class:"field-size" %><br>
	<h4> Opinion</h4>
	<%= f.text_area :opinion, class:"field-size" %><br>
	<%= f.submit 'Update Book', class:"field-size btn btn-primary" %><br>
	<%=link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %>
	|
	<%=link_to "Back", books_path %>
	<% end %>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="clearfix">



    <%= render 'books/list', books: @books %>

	<div class="book-index">
		<h2>Books</h2>
		<table class="table table-atriped">
			<tr>
				<th> image</th>
				<th> Title</th>
				<th> Opinion</th>
			</tr>
			<% @books.each do |book| %>
			<tr>
				<td><%= attachment_image_tag book.user, :image, class: "profile-img", fallback: "no_image.jpg" %></td>
				<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
				<td><%= book.opinion %></td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/books/new.html.erb
<div class="user info">
	<h2>User info</h2>
	<table class="table table-striped user-info-table">
		<tr>
			<th> name</th>
			<td><%= @user.name %></td>
		</tr>
		<tr>
			<th> introduction</th>
			<td>sample introduction</td>
		</tr>
	</table>
</div>

<%= form_for(@book, url:books_path) do |f| %>
<% if @book.errors.any? %>
<div id="error_explanation">
	<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="new-book">
	<h2>New book</h2>
	<%= form_for(@book) do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %><br>
	<h4>Opinion</h4>
	<%= f.text_area :opinion %><br>
	<%= f.submit "Create book" %>
	<% end %>
</div>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p class="show-notice"><%= flash[:notice] %></p>
<% end %>

<div class="clearfix">




    <!-- 部分テンプレート -->

    <div class="main-side">
	<div class="user info">
		<h2>User info</h2>
		<table class="table table-striped user-info-table">

			<div><%= attachment_image_tag @user.user, :image, class: "profile-img2", fallback: "no_image.jpg" %></div>
			<div class="space1"></div>

			<tr>
				<th> name</th>
				<td><%= @user.user.name %></td>
			</tr>
			<tr>
				<th> introduction</th>
				<td><%= @user.user.introduct %></td>
			</tr>
		</table>
		<% if @user.user == current_user %>
		<%=link_to "", edit_user_path(@user), class:"glyphicon glyphicon-wrench field-size btn btn-default edit_user_#{@user.id}" %>
		<% else %>
		<%=link_to "", user_path(current_user.id), class:"glyphicon glyphicon-wrench field-size btn btn-default edit_user_#{@user.id}" %>
		<% end %>
	</div>



	<div class="new-book">
		<%= form_for(@book) do |f| %>
		<h2>New book</h2>
		<h4>Title</h4>
		<%= f.text_field :title, class:"field-size" %><br>
		<h4>Opinion</h4>
		<%= f.text_area :opinion, class:"field-size" %><br>
		<%= f.submit "Create book", class:"field-size btn btn-primary" %>
		<% end %>
	</div>

</div>

<!-- 終わり -->

	<div class="book-show">
		<h2> Books detail</h2>

		<div class="table">
			<table class="table table-striped user-info-table">
				<tr>
					<th></th>
					<th> Tilte</th>
					<th> Opinion</th>
					<th colspan="2"></th>
				</tr>
				<tr>
					<td><%= attachment_image_tag @showbook.user, :image, class:"profile-img", fallback: "no_image.jpg" %><br>
						<span><%= @showbook.user.name %></span>
					</td>
					<td><%= @showbook.title %></td>
					<td><%= @showbook.opinion %></td>
					<% if @showbook.user == current_user %>
					<td><%=link_to "Edit", edit_book_path(@showbook), class:"btn btn-success btn-xs edit_book_#{@showbook.id}" %></td>
					<td><%= link_to "Destroy", book_path(@showbook), method: :delete, class:"btn btn-danger btn-xs destroy_book_#{@showbook.id}", "data-confirm" => "本当に消しますか？" %>
					</td>
					<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <span class= "glyphicon glyphicon-book"></span><b>bookers!</b></h1>

app/views/homes/index.html.erb
<% if flash[:notice] %>
<p class="show-notice"><%= flash[:notice] %></p>
<% end %>

<div class= "home-index">
	<h1>welcome to <span class= "glyphicon glyphicon-book"></span> bookers !!</h1>
	<p>In <span class= "glyphicon glyphicon-book"></span><b>bookers,</b><br>
		you can share and exshange your opinions , inpressions , and emotions<br>
		about varioius books!
	</p>
	<%= link_to " Log in", new_user_session_path, class:"field-size btn btn-primary" %><br>
	<%= link_to " Sign up", new_user_registration_path, class:"field-size btn btn-success" %>
</div>

app/views/homes/show.html.erb
<h2>Home show</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Review</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header class="clearfix">
    <div class="header-left clearfix">
      <div class="header-left-box1"></div>
      <div class="header-left-box2">
        <h4 class="header-left-text"> Bookers</h4>
      </div>
    </div>
    <div class="header-right clearfix">
      <% if user_signed_in? %>
      <div class="header-right-box1"></div>
      <div class="header-right-box2">
        <%= link_to " Home", user_path(current_user.id), class:"nav-list btn btn-dark glyphicon glyphicon-home home" %></div>
      <div class="header-right-box3">
        <%= link_to " Users",users_index_path, class:"nav-list btn btn-dark glyphicon glyphicon-user users" %></div>
      <div class="header-right-box4">
        <%= link_to " Books", books_path, class:"nav-list btn btn-dark glyphicon glyphicon-book books" %></div>
      <div class="header-right-box5">
        <%= link_to " logout", destroy_user_session_path, method: :delete, class:"nav-list btn btn-dark glyphicon glyphicon-log-out logout" %></div>
      <div class="header-right-box6"></div>

      <% else %>
      <div class="header-right-box1"></div>
      <div class="header-right-box2">
        <%= link_to " Home", homes_path, class:"nav-list btn btn-dark glyphicon glyphicon-home home" %>
      </div>
      <div class="header-right-box3">
        <%= link_to " About", home_about_path, class:"nav-list btn btn-dark glyphicon glyphicon-link about" %>
      </div>
      <div class="header-right-box4">
        <%= link_to " sign up", new_user_registration_path, class:"nav-list btn btn-dark glyphicon glyphicon-edit sign_up" %>
      </div>
      <div class="header-right-box5">
        <%= link_to " login", new_user_session_path, class:"nav-list btn btn-dark glyphicon glyphicon-log-in sign_in" %>
      </div>
      <div class="header-right-box6"></div>

      <% end %>
    </div>
  </header>


  <main>

    <%= yield %>

  </main>

  <footer>
    <h4> CopyRight Infratop.inc</h4>
  </footer>


</body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>

<div class="user-edit">

	<%= form_for(@user) do |f| %>
		<% if @user.errors.any? %>
		  <div id="error_explanation" class="alert alert-danger">
		    <ul>
		      <% @user.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
	<span> Name</span><br>
	<%= f.text_field :name %>

	<div class="space1"></div>

	<span> Introduction</span><br>
	<%= f.text_area :introduct, cols:"24" %>

	<div class="space1"></div>

	<span> image</span><br>
	<%= f.attachment_field :image %>

	<div class="space1"></div>

	<%= f.submit 'Update User', class:"btn btn-default" %>

	<% end %>
</div>

app/views/users/index.html.erb
<div class="clearfix">
	<div class="main-side">

		<div class="user info">
			<h2>User info</h2>
			<table class="table table-striped user-info-table">
				<div><%= attachment_image_tag @user, :image, class: "profile-img2", fallback: "no_image.jpg" %></div>
				<div class="space1"></div>
				<tr>
					<th> name</th>
					<td><%= @user.name %></td>
				</tr>
				<tr>
					<th> introduction</th>
					<td><%= @user.introduct %></td>
				</tr>
			</table>
			<%=link_to "", edit_user_path(@user), class:"glyphicon glyphicon-wrench field-size btn btn-default edit_user_#{@user.id}" %>
		</div>

		<%= form_for(@book, url:books_path) do |f| %>
		<% if @book.errors.any? %>
		<div id="error_explanation">
			<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<div class="new-book">
			<h2>New book</h2>
			<%= form_for(@book) do |f| %>
			<h4>Title</h4>
			<%= f.text_field :title, class:"field-size" %><br>
			<h4>Opinion</h4>
			<%= f.text_area :opinion, class:"field-size" %><br>
			<%= f.submit "Create book", class:"field-size btn btn-primary" %>
			<% end %>
		</div>
		<% end %>

	</div>

	<div class="user-index">
		<h2>Users</h2>
		<div class="table">
			<table class="table table-striped">
				<tr>
					<th> image</th>
					<th> name</th>
					<th></th>
				</tr>
				<% @users.each do |user| %>
				<tr>
					<th><%= attachment_image_tag user, :image, class: "profile-img", fallback: "no_image.jpg" %></th>
					<th><%= user.name %></th>
					<th><%=link_to "Show", user_path(user), class: "user_#{user.id}" %></th>
				</tr>
				<% end %>
			</table>
		</div>
	</div>

app/views/users/new.html.erb
<h2>Users#new</h2>

app/views/users/show.html.erb
<% if flash[:notice] %>
<p class="show-notice"><%= flash[:notice] %></p>
<% end %>

<div class="clearfix">
<div class="main-side">

	<div class="user info">
		<h2>User info</h2>
		<table class="table table-striped user-info-table">

			<div><%= attachment_image_tag @user, :image, class: "profile-img2", fallback: "no_image.jpg" %></div>
			<div class="space1"></div>

			<tr>
				<th> name</th>
				<td><%= @user.name %></td>
			</tr>
			<tr>
				<th> introduction</th>
				<td><%= @user.introduct %></td>
			</tr>
		</table>
		<% if @user == current_user %>
		<%=link_to "", edit_user_path(@user), class:"glyphicon glyphicon-wrench field-size btn btn-default edit_user_#{@user.id}" %>
		<% else %>
		<%=link_to "", user_path(current_user.id), class:"glyphicon glyphicon-wrench field-size btn btn-default edit_user_#{@user.id}" %>
		<% end %>
	</div>

	<%= form_for(@book, url:books_path) do |f| %>
	<% if @book.errors.any? %>
	<div id="error_explanation">
		<h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
		<ul>
			<% @book.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="new-book">
		<h2>New book</h2>
		<%= form_for(@book) do |f| %>
		<h4>Title</h4>
		<%= f.text_field :title, class:"field-size" %><br>
		<h4>Opinion</h4>
		<%= f.text_area :opinion, class:"field-size" %><br>
		<%= f.submit "Create book", class:"field-size btn btn-primary" %>
		<% end %>
	</div>
	<% end %>

</div>


<div class="user-show">
	<h2>Books</h2>
	<table class="table table-atriped">
		<tr>
			<th> image</th>
			<th> Title</th>
			<th> Opinion</th>
		</tr>
		<% @books.each do |book| %>
		<tr>
			<td><%= attachment_image_tag @user, :image, class: "profile-img", fallback: "no_image.jpg" %></td>
			<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
			<td><%= book.opinion %></td>
		</tr>
		<% end %>

	</table>
</div>

</div>